// Font
export const FontSizeXLarge = '2rem'
export const FontSizeLarge = '1.5rem'
export const FontSizeBig = '1.3rem'
export const FontSizeMedium = '1.1rem'
export const FontSizeSmall = '1rem'
export const FontSizeMicro = '0.85rem'
export const FontSizeTiny = '0.8rem'
export const FontSizeNano = '0.65rem'
export const FontSizeMin = '0.5rem'
